export default mockItems = {
	a39159: {
		id: 'a39159',
		modelId: 'Lampius-a39159',
		modelName: 'Lampius-a39159',
		modelType: 'gltf',
		position: [2, 0, 3],
		rotation: [0, 0, 0],
		isSelected: false,
		isVisible: true,
		glowPosition: [0, 4, 0],
		glowRadius: 0,
		isGlowing: true,
		hasGlow: true,
		glowColor: 'hotPink',
		glowIntensity: 4,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'3d-glasses': {
		id: '3d-glasses',
		modelId: '3d-glasses',
		modelName: '3d-glasses',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [2, 0, 3],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'acoustic-foam-panel': {
		id: 'acoustic-foam-panel',
		modelId: 'acoustic-foam-panel',
		modelName: 'acoustic-foam-panel',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [7, 0, -2],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'acoustic-panel': {
		id: 'acoustic-panel',
		modelId: 'acoustic-panel',
		modelName: 'acoustic-panel',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [-5, 0, -7],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'ai-npc': {
		id: 'ai-npc',
		modelId: 'ai-npc',
		modelName: 'ai-npc',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [9, 0, 1],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'aircraft-door': {
		id: 'aircraft-door',
		modelId: 'aircraft-door',
		modelName: 'aircraft-door',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [-8, 0, 4],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	amnethyst: {
		id: 'amnethyst',
		modelId: 'amnethyst',
		modelName: 'amnethyst',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [4, 0, -6],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'anatomy-art': {
		id: 'anatomy-art',
		modelId: 'anatomy-art',
		modelName: 'anatomy-art',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [-1, 0, 8],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	angel: {
		id: 'angel',
		modelId: 'angel',
		modelName: 'angel',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [6, 0, 7],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'anime-character': {
		id: 'anime-character',
		modelId: 'anime-character',
		modelName: 'anime-character',
		modelType: 'gltf',
		glowPosition: [0, 0, 0],
		glowRadius: 0,
		isGlowing: false,
		position: [-7, 0, -3],
		rotation: [0, 0, 0],
		hasGlow: false,
		isSelected: false,
		isVisible: true,
		glowColor: '#ffffff',
		glowIntensity: 0,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-2': {
		id: 'lamp-2',
		modelId: 'lamp-2',
		modelName: 'lamp-2',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [3, 0, -8],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'yellow',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-3': {
		id: 'lamp-3',
		modelId: 'lamp-3',
		modelName: 'lamp-3',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-4, 0, 9],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'orange',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-4': {
		id: 'lamp-4',
		modelId: 'lamp-4',
		modelName: 'lamp-4',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [8, 0, -5],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'white',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-5': {
		id: 'lamp-5',
		modelId: 'lamp-5',
		modelName: 'lamp-5',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-9, 0, 2],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'blue',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-6': {
		id: 'lamp-6',
		modelId: 'lamp-6',
		modelName: 'lamp-6',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [1, 0, 11],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'green',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-7': {
		id: 'lamp-7',
		modelId: 'lamp-7',
		modelName: 'lamp-7',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-6, 0, -9],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'purple',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-8': {
		id: 'lamp-8',
		modelId: 'lamp-8',
		modelName: 'lamp-8',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [10, 0, 6],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'red',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-9': {
		id: 'lamp-9',
		modelId: 'lamp-9',
		modelName: 'lamp-9',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-2, 0, -4],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'cyan',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-10': {
		id: 'lamp-10',
		modelId: 'lamp-10',
		modelName: 'lamp-10',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [5, 0, 10],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'magenta',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-11': {
		id: 'lamp-11',
		modelId: 'lamp-11',
		modelName: 'lamp-11',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-10, 0, -1],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'lime',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-12': {
		id: 'lamp-12',
		modelId: 'lamp-12',
		modelName: 'lamp-12',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [11, 0, -7],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'teal',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	},
	'lamp-13': {
		id: 'lamp-13',
		modelId: 'lamp-13',
		modelName: 'lamp-13',
		modelType: 'gltf',
		glowPosition: [0, 4, 0],
		glowRadius: 5,
		isGlowing: true,
		position: [-11, 0, 8],
		rotation: [0, 0, 0],
		hasGlow: true,
		isSelected: false,
		isVisible: true,
		glowColor: 'gold',
		glowIntensity: 2,
		opacity: 1,
		scale: [1, 1, 1],
		meshId: ''
	}
}
